### ISSUE TITLE
Why "Test Host IPMI Inband Interface Send Boot Progress Code Command" output should Be Equal   ${0xAE}?

### ISSUE THREAD

**Issue by solonfan** [ARM-software/sbmr-acs#27]
With testing sbmr test case [Test Host IPMI Inband Interface Send Boot Progress Code Command],I meet below error:
IndexError: list index out of range
&
BuiltIn . Should Be Equal   ${output}    ${0xAE}
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/c7df18b1-1b9f-4c76-ad06-09a128bbbdcf)

By checking sbmr test case source,the output should be eaqule to  ${0xAE},I wonder if these cases unreasonable determine?
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/01f38ef6-437a-4aa5-9e35-285650bafb27)

**Comment by amrathesh** [comment]
Hi @solonfan 

The expected response from the Send Boot Progress Code command is a completion code (0x00h or 0x80h) followed by the group extension defining body (0xAEh) [1]. Since we use ipmitool to issue the command, the tool by default truncates the completion code and outputs only the response body; hence we expect stdout[0] to be 0xAEh.

Upon examining the log, I see that when running the Send Boot Progress Code command, the system is not returning any output, resulting in an IndexError [2].
 
Additionally, I noticed from the logs that the Netfn|Cmd used is 0x30 0x08. I suspect some local changes have been made, and it should be 0x2C 0x02 as defined by SBMR for compliance.
 
[1] SBMR Section F.1.1 https://developer.arm.com/documentation/den0069/latest/ 
[2] https://github.com/ARM-software/sbmr-acs/blob/69a539c0c8a28002d71c15fd0a238be4d6428e60/lib/ipmi_shell_client.py#L186
 
Thanks, 
Amrathesh
Behalf of Arm System Compliance Team

**Comment by amrathesh** [comment]
Hi @solonfan,

The issue has been marked as closed. If you have any comments or feedback, please reopen the issue and reply.

Thanks, 
Amrathesh
Behalf of Arm System Compliance Team
