### ISSUE TITLE
Send Platform Error Record NetFn/CMD conflict

### ISSUE THREAD

**Issue by solonfan** [ARM-software/sbmr-acs#28]
Does sbmr ipmi net/cmd define conflict with Get Manager Certificate Fingerprint?  They are defined with same netfn & cmd.
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/690a6df7-909c-4bfe-8d96-287e0a7eb3e8)
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/9beb8447-23bb-43a6-a8ef-48e09d5c09e4)

And from sbmr test case,
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/3802df92-58b4-4733-a74a-7d4ab37baed0)
Why need output date[0] eaqual to &[0xae]?
![image](https://github.com/ARM-software/sbmr-acs/assets/15608567/f12cea7a-5f65-4321-bc0f-d86b8a3878c5)

**Comment by amrathesh** [comment]
Hi @solonfan,

The Network Function code "0x2Ch" is used for the Group extension. The first data byte position in requests and responses under this network function identifies the defining body that specifies command functionality.
The mentioned IPMI commands use this NetFn and have different "Group extension defining bodies" differentiating them in their functionality.
 
_Why does the output data[0] need to equal &[0xAE]?_
Since ACS uses ipmitool, the tool truncates the completion code and outputs only the response body; hence we expect stdout[0] to be 0xAEh as defined in SBMR [1] for the response body.
 
[1] SBMR Section F.1.1 https://developer.arm.com/documentation/den0069/latest/
 
Thanks, Amrathesh
Behalf of Arm System Compliance Team

**Comment by amrathesh** [comment]
Hi @solonfan,

The issue has been marked as closed. If you have any comments or feedback, please reopen the issue and reply.

Thanks, 
Amrathesh
Behalf of Arm System Compliance Team
