### ISSUE TITLE
M21_USB_1 : Support more customized parameters in InsertMedia request

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#4]
Need to enable VirtualMedia functionality via Redfish before running test. Also, add more customized parameters, such as "TransferProtocolType", in InsertMedia request.

Reference : https://redfish.dmtf.org/schemas/v1/VirtualMedia.v1_6_2.json
File : https://github.com/ARM-software/sbmr-acs/blob/main/redfish/test_redfish_virtual_media.robot#L28

**Comment by amrathesh** [comment]
Hi @gtossk2, 

We have modified the Virtual Media test to enable VirtualMedia Protocol prior to mounting the media, and added custom parameters for InsertMedia patching, that can be configured by ACS user by editing config file.

Please review #11 

Thanks & Regards,
ACS Team

**Comment by amrathesh** [comment]
Hi @gtossk2,

The solution for the issue is merged with commit https://github.com/ARM-software/sbmr-acs/commit/079f8a33c6845483af144893deca89ffe6b0bbbe , To test out the solution, one can download the zipped repo artifact from https://github.com/ARM-software/sbmr-acs/actions/runs/7553206288.

Regards,
ACS Team
